package nl.esciencecenter.eecology.classification.db.doa.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.model.classification.ClassificationPkey;
import nl.esciencecenter.eecology.classification.db.model.classification.ClassificationPkeyExample;
import org.apache.ibatis.annotations.Param;

public interface ClassificationPkeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int countByExample(ClassificationPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByExample(ClassificationPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insert(ClassificationPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insertSelective(ClassificationPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    List<ClassificationPkey> selectByExample(ClassificationPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExampleSelective(@Param("record") ClassificationPkey record, @Param("example") ClassificationPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExample(@Param("record") ClassificationPkey record, @Param("example") ClassificationPkeyExample example);
}