package nl.esciencecenter.eecology.classification.db.doa.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.model.classification.ClassificationCollection;
import nl.esciencecenter.eecology.classification.db.model.classification.ClassificationCollectionExample;
import nl.esciencecenter.eecology.classification.db.model.classification.ClassificationCollectionKey;
import org.apache.ibatis.annotations.Param;

public interface ClassificationCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int countByExample(ClassificationCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByExample(ClassificationCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByPrimaryKey(ClassificationCollectionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insert(ClassificationCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insertSelective(ClassificationCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    List<ClassificationCollection> selectByExample(ClassificationCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    ClassificationCollection selectByPrimaryKey(ClassificationCollectionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExampleSelective(@Param("record") ClassificationCollection record, @Param("example") ClassificationCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExample(@Param("record") ClassificationCollection record, @Param("example") ClassificationCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByPrimaryKeySelective(ClassificationCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByPrimaryKey(ClassificationCollection record);
}