package nl.esciencecenter.eecology.classification.db.doa.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.model.classification.ClassifierClassifierIdSeq;
import nl.esciencecenter.eecology.classification.db.model.classification.ClassifierClassifierIdSeqExample;
import org.apache.ibatis.annotations.Param;

public interface ClassifierClassifierIdSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_classifier_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int countByExample(ClassifierClassifierIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_classifier_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByExample(ClassifierClassifierIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_classifier_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insert(ClassifierClassifierIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_classifier_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insertSelective(ClassifierClassifierIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_classifier_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    List<ClassifierClassifierIdSeq> selectByExample(ClassifierClassifierIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_classifier_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExampleSelective(@Param("record") ClassifierClassifierIdSeq record, @Param("example") ClassifierClassifierIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_classifier_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExample(@Param("record") ClassifierClassifierIdSeq record, @Param("example") ClassifierClassifierIdSeqExample example);
}