package nl.esciencecenter.eecology.classification.db.doa.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.model.classification.ClassifierType;
import nl.esciencecenter.eecology.classification.db.model.classification.ClassifierTypeExample;
import org.apache.ibatis.annotations.Param;

public interface ClassifierTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_type
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int countByExample(ClassifierTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_type
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByExample(ClassifierTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_type
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByPrimaryKey(Integer class_type_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_type
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insert(ClassifierType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_type
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insertSelective(ClassifierType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_type
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    List<ClassifierType> selectByExample(ClassifierTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_type
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    ClassifierType selectByPrimaryKey(Integer class_type_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_type
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExampleSelective(@Param("record") ClassifierType record, @Param("example") ClassifierTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_type
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExample(@Param("record") ClassifierType record, @Param("example") ClassifierTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_type
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByPrimaryKeySelective(ClassifierType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_type
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByPrimaryKey(ClassifierType record);
}