package nl.esciencecenter.eecology.classification.db.doa.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.model.classification.ClassificationCollectionPkey;
import nl.esciencecenter.eecology.classification.db.model.classification.ClassificationCollectionPkeyExample;
import org.apache.ibatis.annotations.Param;

public interface ClassificationCollectionPkeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int countByExample(ClassificationCollectionPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByExample(ClassificationCollectionPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insert(ClassificationCollectionPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insertSelective(ClassificationCollectionPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    List<ClassificationCollectionPkey> selectByExample(ClassificationCollectionPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExampleSelective(@Param("record") ClassificationCollectionPkey record, @Param("example") ClassificationCollectionPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExample(@Param("record") ClassificationCollectionPkey record, @Param("example") ClassificationCollectionPkeyExample example);
}