package nl.esciencecenter.eecology.classification.db.doa.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.model.classification.CollectionCollectionIdSeq;
import nl.esciencecenter.eecology.classification.db.model.classification.CollectionCollectionIdSeqExample;
import org.apache.ibatis.annotations.Param;

public interface CollectionCollectionIdSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_collection_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int countByExample(CollectionCollectionIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_collection_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByExample(CollectionCollectionIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_collection_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insert(CollectionCollectionIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_collection_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insertSelective(CollectionCollectionIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_collection_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    List<CollectionCollectionIdSeq> selectByExample(CollectionCollectionIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_collection_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExampleSelective(@Param("record") CollectionCollectionIdSeq record, @Param("example") CollectionCollectionIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_collection_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExample(@Param("record") CollectionCollectionIdSeq record, @Param("example") CollectionCollectionIdSeqExample example);
}