package nl.esciencecenter.eecology.classification.db.doa.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.model.classification.Collection;
import nl.esciencecenter.eecology.classification.db.model.classification.CollectionExample;
import org.apache.ibatis.annotations.Param;

public interface CollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int countByExample(CollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByExample(CollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByPrimaryKey(Integer collection_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insert(Collection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insertSelective(Collection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    List<Collection> selectByExample(CollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    Collection selectByPrimaryKey(Integer collection_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExampleSelective(@Param("record") Collection record, @Param("example") CollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExample(@Param("record") Collection record, @Param("example") CollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByPrimaryKeySelective(Collection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByPrimaryKey(Collection record);
}