package nl.esciencecenter.eecology.classification.db.doa.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.model.classification.FeatureValuePkey;
import nl.esciencecenter.eecology.classification.db.model.classification.FeatureValuePkeyExample;
import org.apache.ibatis.annotations.Param;

public interface FeatureValuePkeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int countByExample(FeatureValuePkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByExample(FeatureValuePkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insert(FeatureValuePkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insertSelective(FeatureValuePkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    List<FeatureValuePkey> selectByExample(FeatureValuePkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExampleSelective(@Param("record") FeatureValuePkey record, @Param("example") FeatureValuePkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExample(@Param("record") FeatureValuePkey record, @Param("example") FeatureValuePkeyExample example);
}