package nl.esciencecenter.eecology.classification.db.doa.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.model.classification.Feature;
import nl.esciencecenter.eecology.classification.db.model.classification.FeatureExample;
import org.apache.ibatis.annotations.Param;

public interface FeatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int countByExample(FeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByExample(FeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByPrimaryKey(Integer feature_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insert(Feature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insertSelective(Feature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    List<Feature> selectByExample(FeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    Feature selectByPrimaryKey(Integer feature_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExampleSelective(@Param("record") Feature record, @Param("example") FeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExample(@Param("record") Feature record, @Param("example") FeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByPrimaryKeySelective(Feature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByPrimaryKey(Feature record);
}