package nl.esciencecenter.eecology.classification.db.doa.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.model.classification.FeatureFeatureIdSeq;
import nl.esciencecenter.eecology.classification.db.model.classification.FeatureFeatureIdSeqExample;
import org.apache.ibatis.annotations.Param;

public interface FeatureFeatureIdSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_feature_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int countByExample(FeatureFeatureIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_feature_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByExample(FeatureFeatureIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_feature_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insert(FeatureFeatureIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_feature_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insertSelective(FeatureFeatureIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_feature_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    List<FeatureFeatureIdSeq> selectByExample(FeatureFeatureIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_feature_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExampleSelective(@Param("record") FeatureFeatureIdSeq record, @Param("example") FeatureFeatureIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_feature_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExample(@Param("record") FeatureFeatureIdSeq record, @Param("example") FeatureFeatureIdSeqExample example);
}