package nl.esciencecenter.eecology.classification.db.doa.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.model.classification.FeatureValue;
import nl.esciencecenter.eecology.classification.db.model.classification.FeatureValueExample;
import nl.esciencecenter.eecology.classification.db.model.classification.FeatureValueKey;
import org.apache.ibatis.annotations.Param;

public interface FeatureValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int countByExample(FeatureValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByExample(FeatureValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByPrimaryKey(FeatureValueKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insert(FeatureValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insertSelective(FeatureValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    List<FeatureValue> selectByExample(FeatureValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    FeatureValue selectByPrimaryKey(FeatureValueKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExampleSelective(@Param("record") FeatureValue record, @Param("example") FeatureValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExample(@Param("record") FeatureValue record, @Param("example") FeatureValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByPrimaryKeySelective(FeatureValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByPrimaryKey(FeatureValue record);
}