package nl.esciencecenter.eecology.classification.db.doa.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.model.classification.FeaturePkey;
import nl.esciencecenter.eecology.classification.db.model.classification.FeaturePkeyExample;
import org.apache.ibatis.annotations.Param;

public interface FeaturePkeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int countByExample(FeaturePkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByExample(FeaturePkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insert(FeaturePkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insertSelective(FeaturePkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    List<FeaturePkey> selectByExample(FeaturePkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExampleSelective(@Param("record") FeaturePkey record, @Param("example") FeaturePkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExample(@Param("record") FeaturePkey record, @Param("example") FeaturePkeyExample example);
}