package nl.esciencecenter.eecology.classification.db.doa.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.model.classification.JobSelectionExample;
import nl.esciencecenter.eecology.classification.db.model.classification.JobSelectionKey;
import org.apache.ibatis.annotations.Param;

public interface JobSelectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int countByExample(JobSelectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByExample(JobSelectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByPrimaryKey(JobSelectionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insert(JobSelectionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insertSelective(JobSelectionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    List<JobSelectionKey> selectByExample(JobSelectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExampleSelective(@Param("record") JobSelectionKey record, @Param("example") JobSelectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExample(@Param("record") JobSelectionKey record, @Param("example") JobSelectionExample example);
}