package nl.esciencecenter.eecology.classification.db.doa.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.model.classification.LabelLabelIdSeq;
import nl.esciencecenter.eecology.classification.db.model.classification.LabelLabelIdSeqExample;
import org.apache.ibatis.annotations.Param;

public interface LabelLabelIdSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int countByExample(LabelLabelIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByExample(LabelLabelIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insert(LabelLabelIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insertSelective(LabelLabelIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    List<LabelLabelIdSeq> selectByExample(LabelLabelIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExampleSelective(@Param("record") LabelLabelIdSeq record, @Param("example") LabelLabelIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExample(@Param("record") LabelLabelIdSeq record, @Param("example") LabelLabelIdSeqExample example);
}