package nl.esciencecenter.eecology.classification.db.doa.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.model.classification.LabelSchema;
import nl.esciencecenter.eecology.classification.db.model.classification.LabelSchemaExample;
import org.apache.ibatis.annotations.Param;

public interface LabelSchemaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int countByExample(LabelSchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByExample(LabelSchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByPrimaryKey(Integer label_schema_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insert(LabelSchema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insertSelective(LabelSchema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    List<LabelSchema> selectByExample(LabelSchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    LabelSchema selectByPrimaryKey(Integer label_schema_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExampleSelective(@Param("record") LabelSchema record, @Param("example") LabelSchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExample(@Param("record") LabelSchema record, @Param("example") LabelSchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByPrimaryKeySelective(LabelSchema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByPrimaryKey(LabelSchema record);
}