package nl.esciencecenter.eecology.classification.db.doa.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.model.classification.LabelRemapPkey;
import nl.esciencecenter.eecology.classification.db.model.classification.LabelRemapPkeyExample;
import org.apache.ibatis.annotations.Param;

public interface LabelRemapPkeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int countByExample(LabelRemapPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByExample(LabelRemapPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insert(LabelRemapPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insertSelective(LabelRemapPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    List<LabelRemapPkey> selectByExample(LabelRemapPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExampleSelective(@Param("record") LabelRemapPkey record, @Param("example") LabelRemapPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_pkey
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExample(@Param("record") LabelRemapPkey record, @Param("example") LabelRemapPkeyExample example);
}