package nl.esciencecenter.eecology.classification.db.doa.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.model.classification.SegmentAccelerationSegmentAccelerationIdSeq;
import nl.esciencecenter.eecology.classification.db.model.classification.SegmentAccelerationSegmentAccelerationIdSeqExample;
import org.apache.ibatis.annotations.Param;

public interface SegmentAccelerationSegmentAccelerationIdSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration_segment_acceleration_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int countByExample(SegmentAccelerationSegmentAccelerationIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration_segment_acceleration_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByExample(SegmentAccelerationSegmentAccelerationIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration_segment_acceleration_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insert(SegmentAccelerationSegmentAccelerationIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration_segment_acceleration_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insertSelective(SegmentAccelerationSegmentAccelerationIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration_segment_acceleration_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    List<SegmentAccelerationSegmentAccelerationIdSeq> selectByExample(SegmentAccelerationSegmentAccelerationIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration_segment_acceleration_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExampleSelective(@Param("record") SegmentAccelerationSegmentAccelerationIdSeq record, @Param("example") SegmentAccelerationSegmentAccelerationIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration_segment_acceleration_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExample(@Param("record") SegmentAccelerationSegmentAccelerationIdSeq record, @Param("example") SegmentAccelerationSegmentAccelerationIdSeqExample example);
}