package nl.esciencecenter.eecology.classification.db.doa.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.model.classification.SegmentatorSegmentatorIdSeq;
import nl.esciencecenter.eecology.classification.db.model.classification.SegmentatorSegmentatorIdSeqExample;
import org.apache.ibatis.annotations.Param;

public interface SegmentatorSegmentatorIdSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_segmentator_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int countByExample(SegmentatorSegmentatorIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_segmentator_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByExample(SegmentatorSegmentatorIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_segmentator_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insert(SegmentatorSegmentatorIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_segmentator_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insertSelective(SegmentatorSegmentatorIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_segmentator_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    List<SegmentatorSegmentatorIdSeq> selectByExample(SegmentatorSegmentatorIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_segmentator_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExampleSelective(@Param("record") SegmentatorSegmentatorIdSeq record, @Param("example") SegmentatorSegmentatorIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_segmentator_id_seq
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExample(@Param("record") SegmentatorSegmentatorIdSeq record, @Param("example") SegmentatorSegmentatorIdSeqExample example);
}