package nl.esciencecenter.eecology.classification.db.doa.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.model.classification.SegmentatorNameKey;
import nl.esciencecenter.eecology.classification.db.model.classification.SegmentatorNameKeyExample;
import org.apache.ibatis.annotations.Param;

public interface SegmentatorNameKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_name_key
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int countByExample(SegmentatorNameKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_name_key
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int deleteByExample(SegmentatorNameKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_name_key
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insert(SegmentatorNameKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_name_key
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int insertSelective(SegmentatorNameKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_name_key
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    List<SegmentatorNameKey> selectByExample(SegmentatorNameKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_name_key
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExampleSelective(@Param("record") SegmentatorNameKey record, @Param("example") SegmentatorNameKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_name_key
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    int updateByExample(@Param("record") SegmentatorNameKey record, @Param("example") SegmentatorNameKeyExample example);
}