package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.ClassificationCollectionSegmentIdKey;
import nl.esciencecenter.eecology.classification.db.classification.ClassificationCollectionSegmentIdKeyExample;
import org.apache.ibatis.annotations.Param;

public interface ClassificationCollectionSegmentIdKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(ClassificationCollectionSegmentIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(ClassificationCollectionSegmentIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(ClassificationCollectionSegmentIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(ClassificationCollectionSegmentIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<ClassificationCollectionSegmentIdKey> selectByExample(ClassificationCollectionSegmentIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") ClassificationCollectionSegmentIdKey record, @Param("example") ClassificationCollectionSegmentIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_collection_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") ClassificationCollectionSegmentIdKey record, @Param("example") ClassificationCollectionSegmentIdKeyExample example);
}