package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ClassifierExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table classification.classifier
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table classification.classifier
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table classification.classifier
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public ClassifierExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table classification.classifier
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClassifier_idIsNull() {
            addCriterion("classifier_id is null");
            return (Criteria) this;
        }

        public Criteria andClassifier_idIsNotNull() {
            addCriterion("classifier_id is not null");
            return (Criteria) this;
        }

        public Criteria andClassifier_idEqualTo(Integer value) {
            addCriterion("classifier_id =", value, "classifier_id");
            return (Criteria) this;
        }

        public Criteria andClassifier_idNotEqualTo(Integer value) {
            addCriterion("classifier_id <>", value, "classifier_id");
            return (Criteria) this;
        }

        public Criteria andClassifier_idGreaterThan(Integer value) {
            addCriterion("classifier_id >", value, "classifier_id");
            return (Criteria) this;
        }

        public Criteria andClassifier_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("classifier_id >=", value, "classifier_id");
            return (Criteria) this;
        }

        public Criteria andClassifier_idLessThan(Integer value) {
            addCriterion("classifier_id <", value, "classifier_id");
            return (Criteria) this;
        }

        public Criteria andClassifier_idLessThanOrEqualTo(Integer value) {
            addCriterion("classifier_id <=", value, "classifier_id");
            return (Criteria) this;
        }

        public Criteria andClassifier_idIn(List<Integer> values) {
            addCriterion("classifier_id in", values, "classifier_id");
            return (Criteria) this;
        }

        public Criteria andClassifier_idNotIn(List<Integer> values) {
            addCriterion("classifier_id not in", values, "classifier_id");
            return (Criteria) this;
        }

        public Criteria andClassifier_idBetween(Integer value1, Integer value2) {
            addCriterion("classifier_id between", value1, value2, "classifier_id");
            return (Criteria) this;
        }

        public Criteria andClassifier_idNotBetween(Integer value1, Integer value2) {
            addCriterion("classifier_id not between", value1, value2, "classifier_id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andClass_type_idIsNull() {
            addCriterion("class_type_id is null");
            return (Criteria) this;
        }

        public Criteria andClass_type_idIsNotNull() {
            addCriterion("class_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andClass_type_idEqualTo(Integer value) {
            addCriterion("class_type_id =", value, "class_type_id");
            return (Criteria) this;
        }

        public Criteria andClass_type_idNotEqualTo(Integer value) {
            addCriterion("class_type_id <>", value, "class_type_id");
            return (Criteria) this;
        }

        public Criteria andClass_type_idGreaterThan(Integer value) {
            addCriterion("class_type_id >", value, "class_type_id");
            return (Criteria) this;
        }

        public Criteria andClass_type_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("class_type_id >=", value, "class_type_id");
            return (Criteria) this;
        }

        public Criteria andClass_type_idLessThan(Integer value) {
            addCriterion("class_type_id <", value, "class_type_id");
            return (Criteria) this;
        }

        public Criteria andClass_type_idLessThanOrEqualTo(Integer value) {
            addCriterion("class_type_id <=", value, "class_type_id");
            return (Criteria) this;
        }

        public Criteria andClass_type_idIn(List<Integer> values) {
            addCriterion("class_type_id in", values, "class_type_id");
            return (Criteria) this;
        }

        public Criteria andClass_type_idNotIn(List<Integer> values) {
            addCriterion("class_type_id not in", values, "class_type_id");
            return (Criteria) this;
        }

        public Criteria andClass_type_idBetween(Integer value1, Integer value2) {
            addCriterion("class_type_id between", value1, value2, "class_type_id");
            return (Criteria) this;
        }

        public Criteria andClass_type_idNotBetween(Integer value1, Integer value2) {
            addCriterion("class_type_id not between", value1, value2, "class_type_id");
            return (Criteria) this;
        }

        public Criteria andLabel_schema_idIsNull() {
            addCriterion("label_schema_id is null");
            return (Criteria) this;
        }

        public Criteria andLabel_schema_idIsNotNull() {
            addCriterion("label_schema_id is not null");
            return (Criteria) this;
        }

        public Criteria andLabel_schema_idEqualTo(Integer value) {
            addCriterion("label_schema_id =", value, "label_schema_id");
            return (Criteria) this;
        }

        public Criteria andLabel_schema_idNotEqualTo(Integer value) {
            addCriterion("label_schema_id <>", value, "label_schema_id");
            return (Criteria) this;
        }

        public Criteria andLabel_schema_idGreaterThan(Integer value) {
            addCriterion("label_schema_id >", value, "label_schema_id");
            return (Criteria) this;
        }

        public Criteria andLabel_schema_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("label_schema_id >=", value, "label_schema_id");
            return (Criteria) this;
        }

        public Criteria andLabel_schema_idLessThan(Integer value) {
            addCriterion("label_schema_id <", value, "label_schema_id");
            return (Criteria) this;
        }

        public Criteria andLabel_schema_idLessThanOrEqualTo(Integer value) {
            addCriterion("label_schema_id <=", value, "label_schema_id");
            return (Criteria) this;
        }

        public Criteria andLabel_schema_idIn(List<Integer> values) {
            addCriterion("label_schema_id in", values, "label_schema_id");
            return (Criteria) this;
        }

        public Criteria andLabel_schema_idNotIn(List<Integer> values) {
            addCriterion("label_schema_id not in", values, "label_schema_id");
            return (Criteria) this;
        }

        public Criteria andLabel_schema_idBetween(Integer value1, Integer value2) {
            addCriterion("label_schema_id between", value1, value2, "label_schema_id");
            return (Criteria) this;
        }

        public Criteria andLabel_schema_idNotBetween(Integer value1, Integer value2) {
            addCriterion("label_schema_id not between", value1, value2, "label_schema_id");
            return (Criteria) this;
        }

        public Criteria andSegmentator_idIsNull() {
            addCriterion("segmentator_id is null");
            return (Criteria) this;
        }

        public Criteria andSegmentator_idIsNotNull() {
            addCriterion("segmentator_id is not null");
            return (Criteria) this;
        }

        public Criteria andSegmentator_idEqualTo(Integer value) {
            addCriterion("segmentator_id =", value, "segmentator_id");
            return (Criteria) this;
        }

        public Criteria andSegmentator_idNotEqualTo(Integer value) {
            addCriterion("segmentator_id <>", value, "segmentator_id");
            return (Criteria) this;
        }

        public Criteria andSegmentator_idGreaterThan(Integer value) {
            addCriterion("segmentator_id >", value, "segmentator_id");
            return (Criteria) this;
        }

        public Criteria andSegmentator_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("segmentator_id >=", value, "segmentator_id");
            return (Criteria) this;
        }

        public Criteria andSegmentator_idLessThan(Integer value) {
            addCriterion("segmentator_id <", value, "segmentator_id");
            return (Criteria) this;
        }

        public Criteria andSegmentator_idLessThanOrEqualTo(Integer value) {
            addCriterion("segmentator_id <=", value, "segmentator_id");
            return (Criteria) this;
        }

        public Criteria andSegmentator_idIn(List<Integer> values) {
            addCriterion("segmentator_id in", values, "segmentator_id");
            return (Criteria) this;
        }

        public Criteria andSegmentator_idNotIn(List<Integer> values) {
            addCriterion("segmentator_id not in", values, "segmentator_id");
            return (Criteria) this;
        }

        public Criteria andSegmentator_idBetween(Integer value1, Integer value2) {
            addCriterion("segmentator_id between", value1, value2, "segmentator_id");
            return (Criteria) this;
        }

        public Criteria andSegmentator_idNotBetween(Integer value1, Integer value2) {
            addCriterion("segmentator_id not between", value1, value2, "segmentator_id");
            return (Criteria) this;
        }

        public Criteria andTraining_set_idIsNull() {
            addCriterion("training_set_id is null");
            return (Criteria) this;
        }

        public Criteria andTraining_set_idIsNotNull() {
            addCriterion("training_set_id is not null");
            return (Criteria) this;
        }

        public Criteria andTraining_set_idEqualTo(Integer value) {
            addCriterion("training_set_id =", value, "training_set_id");
            return (Criteria) this;
        }

        public Criteria andTraining_set_idNotEqualTo(Integer value) {
            addCriterion("training_set_id <>", value, "training_set_id");
            return (Criteria) this;
        }

        public Criteria andTraining_set_idGreaterThan(Integer value) {
            addCriterion("training_set_id >", value, "training_set_id");
            return (Criteria) this;
        }

        public Criteria andTraining_set_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("training_set_id >=", value, "training_set_id");
            return (Criteria) this;
        }

        public Criteria andTraining_set_idLessThan(Integer value) {
            addCriterion("training_set_id <", value, "training_set_id");
            return (Criteria) this;
        }

        public Criteria andTraining_set_idLessThanOrEqualTo(Integer value) {
            addCriterion("training_set_id <=", value, "training_set_id");
            return (Criteria) this;
        }

        public Criteria andTraining_set_idIn(List<Integer> values) {
            addCriterion("training_set_id in", values, "training_set_id");
            return (Criteria) this;
        }

        public Criteria andTraining_set_idNotIn(List<Integer> values) {
            addCriterion("training_set_id not in", values, "training_set_id");
            return (Criteria) this;
        }

        public Criteria andTraining_set_idBetween(Integer value1, Integer value2) {
            addCriterion("training_set_id between", value1, value2, "training_set_id");
            return (Criteria) this;
        }

        public Criteria andTraining_set_idNotBetween(Integer value1, Integer value2) {
            addCriterion("training_set_id not between", value1, value2, "training_set_id");
            return (Criteria) this;
        }

        public Criteria andParent_classifier_idIsNull() {
            addCriterion("parent_classifier_id is null");
            return (Criteria) this;
        }

        public Criteria andParent_classifier_idIsNotNull() {
            addCriterion("parent_classifier_id is not null");
            return (Criteria) this;
        }

        public Criteria andParent_classifier_idEqualTo(Integer value) {
            addCriterion("parent_classifier_id =", value, "parent_classifier_id");
            return (Criteria) this;
        }

        public Criteria andParent_classifier_idNotEqualTo(Integer value) {
            addCriterion("parent_classifier_id <>", value, "parent_classifier_id");
            return (Criteria) this;
        }

        public Criteria andParent_classifier_idGreaterThan(Integer value) {
            addCriterion("parent_classifier_id >", value, "parent_classifier_id");
            return (Criteria) this;
        }

        public Criteria andParent_classifier_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("parent_classifier_id >=", value, "parent_classifier_id");
            return (Criteria) this;
        }

        public Criteria andParent_classifier_idLessThan(Integer value) {
            addCriterion("parent_classifier_id <", value, "parent_classifier_id");
            return (Criteria) this;
        }

        public Criteria andParent_classifier_idLessThanOrEqualTo(Integer value) {
            addCriterion("parent_classifier_id <=", value, "parent_classifier_id");
            return (Criteria) this;
        }

        public Criteria andParent_classifier_idIn(List<Integer> values) {
            addCriterion("parent_classifier_id in", values, "parent_classifier_id");
            return (Criteria) this;
        }

        public Criteria andParent_classifier_idNotIn(List<Integer> values) {
            addCriterion("parent_classifier_id not in", values, "parent_classifier_id");
            return (Criteria) this;
        }

        public Criteria andParent_classifier_idBetween(Integer value1, Integer value2) {
            addCriterion("parent_classifier_id between", value1, value2, "parent_classifier_id");
            return (Criteria) this;
        }

        public Criteria andParent_classifier_idNotBetween(Integer value1, Integer value2) {
            addCriterion("parent_classifier_id not between", value1, value2, "parent_classifier_id");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andCreated_onIsNull() {
            addCriterion("created_on is null");
            return (Criteria) this;
        }

        public Criteria andCreated_onIsNotNull() {
            addCriterion("created_on is not null");
            return (Criteria) this;
        }

        public Criteria andCreated_onEqualTo(Date value) {
            addCriterion("created_on =", value, "created_on");
            return (Criteria) this;
        }

        public Criteria andCreated_onNotEqualTo(Date value) {
            addCriterion("created_on <>", value, "created_on");
            return (Criteria) this;
        }

        public Criteria andCreated_onGreaterThan(Date value) {
            addCriterion("created_on >", value, "created_on");
            return (Criteria) this;
        }

        public Criteria andCreated_onGreaterThanOrEqualTo(Date value) {
            addCriterion("created_on >=", value, "created_on");
            return (Criteria) this;
        }

        public Criteria andCreated_onLessThan(Date value) {
            addCriterion("created_on <", value, "created_on");
            return (Criteria) this;
        }

        public Criteria andCreated_onLessThanOrEqualTo(Date value) {
            addCriterion("created_on <=", value, "created_on");
            return (Criteria) this;
        }

        public Criteria andCreated_onIn(List<Date> values) {
            addCriterion("created_on in", values, "created_on");
            return (Criteria) this;
        }

        public Criteria andCreated_onNotIn(List<Date> values) {
            addCriterion("created_on not in", values, "created_on");
            return (Criteria) this;
        }

        public Criteria andCreated_onBetween(Date value1, Date value2) {
            addCriterion("created_on between", value1, value2, "created_on");
            return (Criteria) this;
        }

        public Criteria andCreated_onNotBetween(Date value1, Date value2) {
            addCriterion("created_on not between", value1, value2, "created_on");
            return (Criteria) this;
        }

        public Criteria andCreated_byIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreated_byIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreated_byEqualTo(String value) {
            addCriterion("created_by =", value, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byNotEqualTo(String value) {
            addCriterion("created_by <>", value, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byGreaterThan(String value) {
            addCriterion("created_by >", value, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byLessThan(String value) {
            addCriterion("created_by <", value, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byLike(String value) {
            addCriterion("created_by like", value, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byNotLike(String value) {
            addCriterion("created_by not like", value, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byIn(List<String> values) {
            addCriterion("created_by in", values, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byNotIn(List<String> values) {
            addCriterion("created_by not in", values, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "created_by");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table classification.classifier
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 07 16:43:08 CEST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table classification.classifier
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}