package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.ClassifierTypeClassTypeIdSeq;
import nl.esciencecenter.eecology.classification.db.classification.ClassifierTypeClassTypeIdSeqExample;
import org.apache.ibatis.annotations.Param;

public interface ClassifierTypeClassTypeIdSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_type_class_type_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(ClassifierTypeClassTypeIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_type_class_type_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(ClassifierTypeClassTypeIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_type_class_type_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(ClassifierTypeClassTypeIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_type_class_type_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(ClassifierTypeClassTypeIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_type_class_type_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<ClassifierTypeClassTypeIdSeq> selectByExample(ClassifierTypeClassTypeIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_type_class_type_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") ClassifierTypeClassTypeIdSeq record, @Param("example") ClassifierTypeClassTypeIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_type_class_type_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") ClassifierTypeClassTypeIdSeq record, @Param("example") ClassifierTypeClassTypeIdSeqExample example);
}