package nl.esciencecenter.eecology.classification.db.model.classification;

public class ClassificationCollectionPkey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.classification_collection_pkey.collection_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Integer collection_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.classification_collection_pkey.segment_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Integer segment_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.classification_collection_pkey.collection_id
     *
     * @return the value of classification.classification_collection_pkey.collection_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Integer getCollection_id() {
        return collection_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classification_collection_pkey.collection_id
     *
     * @param collection_id the value for classification.classification_collection_pkey.collection_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setCollection_id(Integer collection_id) {
        this.collection_id = collection_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.classification_collection_pkey.segment_id
     *
     * @return the value of classification.classification_collection_pkey.segment_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Integer getSegment_id() {
        return segment_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classification_collection_pkey.segment_id
     *
     * @param segment_id the value for classification.classification_collection_pkey.segment_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setSegment_id(Integer segment_id) {
        this.segment_id = segment_id;
    }
}