package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.ClassifierLabelSchemaIdKey;
import nl.esciencecenter.eecology.classification.db.classification.ClassifierLabelSchemaIdKeyExample;
import org.apache.ibatis.annotations.Param;

public interface ClassifierLabelSchemaIdKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(ClassifierLabelSchemaIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(ClassifierLabelSchemaIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(ClassifierLabelSchemaIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(ClassifierLabelSchemaIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<ClassifierLabelSchemaIdKey> selectByExample(ClassifierLabelSchemaIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") ClassifierLabelSchemaIdKey record, @Param("example") ClassifierLabelSchemaIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") ClassifierLabelSchemaIdKey record, @Param("example") ClassifierLabelSchemaIdKeyExample example);
}