package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.ClassificationSegmentIdKey;
import nl.esciencecenter.eecology.classification.db.classification.ClassificationSegmentIdKeyExample;
import org.apache.ibatis.annotations.Param;

public interface ClassificationSegmentIdKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(ClassificationSegmentIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(ClassificationSegmentIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(ClassificationSegmentIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(ClassificationSegmentIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<ClassificationSegmentIdKey> selectByExample(ClassificationSegmentIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") ClassificationSegmentIdKey record, @Param("example") ClassificationSegmentIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classification_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") ClassificationSegmentIdKey record, @Param("example") ClassificationSegmentIdKeyExample example);
}