package nl.esciencecenter.eecology.classification.db.model.classification;

public class ClassificationPkey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.classification_pkey.job_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Integer job_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.classification_pkey.segment_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Integer segment_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.classification_pkey.job_id
     *
     * @return the value of classification.classification_pkey.job_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Integer getJob_id() {
        return job_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classification_pkey.job_id
     *
     * @param job_id the value for classification.classification_pkey.job_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setJob_id(Integer job_id) {
        this.job_id = job_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.classification_pkey.segment_id
     *
     * @return the value of classification.classification_pkey.segment_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Integer getSegment_id() {
        return segment_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classification_pkey.segment_id
     *
     * @param segment_id the value for classification.classification_pkey.segment_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setSegment_id(Integer segment_id) {
        this.segment_id = segment_id;
    }
}