package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.Classifier;
import nl.esciencecenter.eecology.classification.db.classification.ClassifierExample;
import org.apache.ibatis.annotations.Param;

public interface ClassifierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(ClassifierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(ClassifierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByPrimaryKey(Integer classifier_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(Classifier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(Classifier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<Classifier> selectByExampleWithBLOBs(ClassifierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<Classifier> selectByExample(ClassifierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    Classifier selectByPrimaryKey(Integer classifier_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") Classifier record, @Param("example") ClassifierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleWithBLOBs(@Param("record") Classifier record, @Param("example") ClassifierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") Classifier record, @Param("example") ClassifierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByPrimaryKeySelective(Classifier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByPrimaryKeyWithBLOBs(Classifier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByPrimaryKey(Classifier record);
}