package nl.esciencecenter.eecology.classification.db.model.classification;

public class ClassifierTypePkey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.classifier_type_pkey.class_type_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Integer class_type_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.classifier_type_pkey.class_type_id
     *
     * @return the value of classification.classifier_type_pkey.class_type_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Integer getClass_type_id() {
        return class_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classifier_type_pkey.class_type_id
     *
     * @param class_type_id the value for classification.classifier_type_pkey.class_type_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setClass_type_id(Integer class_type_id) {
        this.class_type_id = class_type_id;
    }
}