package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.ClassifierTrainingSetIdKey;
import nl.esciencecenter.eecology.classification.db.classification.ClassifierTrainingSetIdKeyExample;
import org.apache.ibatis.annotations.Param;

public interface ClassifierTrainingSetIdKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_training_set_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(ClassifierTrainingSetIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_training_set_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(ClassifierTrainingSetIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_training_set_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(ClassifierTrainingSetIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_training_set_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(ClassifierTrainingSetIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_training_set_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<ClassifierTrainingSetIdKey> selectByExample(ClassifierTrainingSetIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_training_set_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") ClassifierTrainingSetIdKey record, @Param("example") ClassifierTrainingSetIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.classifier_training_set_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") ClassifierTrainingSetIdKey record, @Param("example") ClassifierTrainingSetIdKeyExample example);
}