package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.Date;

public class Classifier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.classifier.classifier_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Integer classifier_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.classifier.name
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.classifier.class_type_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Integer class_type_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.classifier.label_schema_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Integer label_schema_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.classifier.segmentator_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Integer segmentator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.classifier.training_set_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Integer training_set_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.classifier.parent_classifier_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Integer parent_classifier_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.classifier.description
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.classifier.created_on
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Date created_on;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.classifier.created_by
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private String created_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.classifier.weka_object
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private byte[] weka_object;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.classifier.classifier_id
     *
     * @return the value of classification.classifier.classifier_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Integer getClassifier_id() {
        return classifier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classifier.classifier_id
     *
     * @param classifier_id the value for classification.classifier.classifier_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setClassifier_id(Integer classifier_id) {
        this.classifier_id = classifier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.classifier.name
     *
     * @return the value of classification.classifier.name
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classifier.name
     *
     * @param name the value for classification.classifier.name
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.classifier.class_type_id
     *
     * @return the value of classification.classifier.class_type_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Integer getClass_type_id() {
        return class_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classifier.class_type_id
     *
     * @param class_type_id the value for classification.classifier.class_type_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setClass_type_id(Integer class_type_id) {
        this.class_type_id = class_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.classifier.label_schema_id
     *
     * @return the value of classification.classifier.label_schema_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Integer getLabel_schema_id() {
        return label_schema_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classifier.label_schema_id
     *
     * @param label_schema_id the value for classification.classifier.label_schema_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setLabel_schema_id(Integer label_schema_id) {
        this.label_schema_id = label_schema_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.classifier.segmentator_id
     *
     * @return the value of classification.classifier.segmentator_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Integer getSegmentator_id() {
        return segmentator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classifier.segmentator_id
     *
     * @param segmentator_id the value for classification.classifier.segmentator_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setSegmentator_id(Integer segmentator_id) {
        this.segmentator_id = segmentator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.classifier.training_set_id
     *
     * @return the value of classification.classifier.training_set_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Integer getTraining_set_id() {
        return training_set_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classifier.training_set_id
     *
     * @param training_set_id the value for classification.classifier.training_set_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setTraining_set_id(Integer training_set_id) {
        this.training_set_id = training_set_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.classifier.parent_classifier_id
     *
     * @return the value of classification.classifier.parent_classifier_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Integer getParent_classifier_id() {
        return parent_classifier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classifier.parent_classifier_id
     *
     * @param parent_classifier_id the value for classification.classifier.parent_classifier_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setParent_classifier_id(Integer parent_classifier_id) {
        this.parent_classifier_id = parent_classifier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.classifier.description
     *
     * @return the value of classification.classifier.description
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classifier.description
     *
     * @param description the value for classification.classifier.description
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.classifier.created_on
     *
     * @return the value of classification.classifier.created_on
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Date getCreated_on() {
        return created_on;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classifier.created_on
     *
     * @param created_on the value for classification.classifier.created_on
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setCreated_on(Date created_on) {
        this.created_on = created_on;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.classifier.created_by
     *
     * @return the value of classification.classifier.created_by
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public String getCreated_by() {
        return created_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classifier.created_by
     *
     * @param created_by the value for classification.classifier.created_by
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setCreated_by(String created_by) {
        this.created_by = created_by == null ? null : created_by.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.classifier.weka_object
     *
     * @return the value of classification.classifier.weka_object
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public byte[] getWeka_object() {
        return weka_object;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classifier.weka_object
     *
     * @param weka_object the value for classification.classifier.weka_object
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setWeka_object(byte[] weka_object) {
        this.weka_object = weka_object;
    }
}