package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.CollectionGroupCollectionGroupIdSeq;
import nl.esciencecenter.eecology.classification.db.classification.CollectionGroupCollectionGroupIdSeqExample;
import org.apache.ibatis.annotations.Param;

public interface CollectionGroupCollectionGroupIdSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group_collection_group_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(CollectionGroupCollectionGroupIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group_collection_group_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(CollectionGroupCollectionGroupIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group_collection_group_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(CollectionGroupCollectionGroupIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group_collection_group_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(CollectionGroupCollectionGroupIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group_collection_group_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<CollectionGroupCollectionGroupIdSeq> selectByExample(CollectionGroupCollectionGroupIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group_collection_group_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") CollectionGroupCollectionGroupIdSeq record, @Param("example") CollectionGroupCollectionGroupIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group_collection_group_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") CollectionGroupCollectionGroupIdSeq record, @Param("example") CollectionGroupCollectionGroupIdSeqExample example);
}