package nl.esciencecenter.eecology.classification.db.model.classification;

public class CollectionGroupCollectionGroupIdSeq {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.collection_group_collection_group_id_seq.sequence_name
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private String sequence_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.collection_group_collection_group_id_seq.last_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Long last_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.collection_group_collection_group_id_seq.start_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Long start_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.collection_group_collection_group_id_seq.increment_by
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Long increment_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.collection_group_collection_group_id_seq.max_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Long max_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.collection_group_collection_group_id_seq.min_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Long min_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.collection_group_collection_group_id_seq.cache_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Long cache_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.collection_group_collection_group_id_seq.log_cnt
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Long log_cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.collection_group_collection_group_id_seq.is_cycled
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Boolean is_cycled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.collection_group_collection_group_id_seq.is_called
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Boolean is_called;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.collection_group_collection_group_id_seq.sequence_name
     *
     * @return the value of classification.collection_group_collection_group_id_seq.sequence_name
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public String getSequence_name() {
        return sequence_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.collection_group_collection_group_id_seq.sequence_name
     *
     * @param sequence_name the value for classification.collection_group_collection_group_id_seq.sequence_name
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setSequence_name(String sequence_name) {
        this.sequence_name = sequence_name == null ? null : sequence_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.collection_group_collection_group_id_seq.last_value
     *
     * @return the value of classification.collection_group_collection_group_id_seq.last_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Long getLast_value() {
        return last_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.collection_group_collection_group_id_seq.last_value
     *
     * @param last_value the value for classification.collection_group_collection_group_id_seq.last_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setLast_value(Long last_value) {
        this.last_value = last_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.collection_group_collection_group_id_seq.start_value
     *
     * @return the value of classification.collection_group_collection_group_id_seq.start_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Long getStart_value() {
        return start_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.collection_group_collection_group_id_seq.start_value
     *
     * @param start_value the value for classification.collection_group_collection_group_id_seq.start_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setStart_value(Long start_value) {
        this.start_value = start_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.collection_group_collection_group_id_seq.increment_by
     *
     * @return the value of classification.collection_group_collection_group_id_seq.increment_by
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Long getIncrement_by() {
        return increment_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.collection_group_collection_group_id_seq.increment_by
     *
     * @param increment_by the value for classification.collection_group_collection_group_id_seq.increment_by
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setIncrement_by(Long increment_by) {
        this.increment_by = increment_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.collection_group_collection_group_id_seq.max_value
     *
     * @return the value of classification.collection_group_collection_group_id_seq.max_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Long getMax_value() {
        return max_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.collection_group_collection_group_id_seq.max_value
     *
     * @param max_value the value for classification.collection_group_collection_group_id_seq.max_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setMax_value(Long max_value) {
        this.max_value = max_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.collection_group_collection_group_id_seq.min_value
     *
     * @return the value of classification.collection_group_collection_group_id_seq.min_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Long getMin_value() {
        return min_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.collection_group_collection_group_id_seq.min_value
     *
     * @param min_value the value for classification.collection_group_collection_group_id_seq.min_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setMin_value(Long min_value) {
        this.min_value = min_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.collection_group_collection_group_id_seq.cache_value
     *
     * @return the value of classification.collection_group_collection_group_id_seq.cache_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Long getCache_value() {
        return cache_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.collection_group_collection_group_id_seq.cache_value
     *
     * @param cache_value the value for classification.collection_group_collection_group_id_seq.cache_value
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setCache_value(Long cache_value) {
        this.cache_value = cache_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.collection_group_collection_group_id_seq.log_cnt
     *
     * @return the value of classification.collection_group_collection_group_id_seq.log_cnt
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Long getLog_cnt() {
        return log_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.collection_group_collection_group_id_seq.log_cnt
     *
     * @param log_cnt the value for classification.collection_group_collection_group_id_seq.log_cnt
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setLog_cnt(Long log_cnt) {
        this.log_cnt = log_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.collection_group_collection_group_id_seq.is_cycled
     *
     * @return the value of classification.collection_group_collection_group_id_seq.is_cycled
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Boolean getIs_cycled() {
        return is_cycled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.collection_group_collection_group_id_seq.is_cycled
     *
     * @param is_cycled the value for classification.collection_group_collection_group_id_seq.is_cycled
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setIs_cycled(Boolean is_cycled) {
        this.is_cycled = is_cycled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.collection_group_collection_group_id_seq.is_called
     *
     * @return the value of classification.collection_group_collection_group_id_seq.is_called
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Boolean getIs_called() {
        return is_called;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.collection_group_collection_group_id_seq.is_called
     *
     * @param is_called the value for classification.collection_group_collection_group_id_seq.is_called
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setIs_called(Boolean is_called) {
        this.is_called = is_called;
    }
}