package nl.esciencecenter.eecology.classification.db.model.classification;

public class CollectionGroupPkey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.collection_group_pkey.collection_group_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Integer collection_group_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.collection_group_pkey.collection_group_id
     *
     * @return the value of classification.collection_group_pkey.collection_group_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Integer getCollection_group_id() {
        return collection_group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.collection_group_pkey.collection_group_id
     *
     * @param collection_group_id the value for classification.collection_group_pkey.collection_group_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setCollection_group_id(Integer collection_group_id) {
        this.collection_group_id = collection_group_id;
    }
}