package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.CollectionGroup;
import nl.esciencecenter.eecology.classification.db.classification.CollectionGroupExample;
import org.apache.ibatis.annotations.Param;

public interface CollectionGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(CollectionGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(CollectionGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByPrimaryKey(Integer collection_group_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(CollectionGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(CollectionGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<CollectionGroup> selectByExample(CollectionGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    CollectionGroup selectByPrimaryKey(Integer collection_group_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") CollectionGroup record, @Param("example") CollectionGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") CollectionGroup record, @Param("example") CollectionGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByPrimaryKeySelective(CollectionGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByPrimaryKey(CollectionGroup record);
}