package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.CollectionGroupPkey;
import nl.esciencecenter.eecology.classification.db.classification.CollectionGroupPkeyExample;
import org.apache.ibatis.annotations.Param;

public interface CollectionGroupPkeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(CollectionGroupPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(CollectionGroupPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(CollectionGroupPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(CollectionGroupPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<CollectionGroupPkey> selectByExample(CollectionGroupPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") CollectionGroupPkey record, @Param("example") CollectionGroupPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.collection_group_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") CollectionGroupPkey record, @Param("example") CollectionGroupPkeyExample example);
}