package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.FeatureClassifierClassifierIdKey;
import nl.esciencecenter.eecology.classification.db.classification.FeatureClassifierClassifierIdKeyExample;
import org.apache.ibatis.annotations.Param;

public interface FeatureClassifierClassifierIdKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier_classifier_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(FeatureClassifierClassifierIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier_classifier_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(FeatureClassifierClassifierIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier_classifier_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(FeatureClassifierClassifierIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier_classifier_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(FeatureClassifierClassifierIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier_classifier_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<FeatureClassifierClassifierIdKey> selectByExample(FeatureClassifierClassifierIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier_classifier_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") FeatureClassifierClassifierIdKey record, @Param("example") FeatureClassifierClassifierIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier_classifier_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") FeatureClassifierClassifierIdKey record, @Param("example") FeatureClassifierClassifierIdKeyExample example);
}