package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.FeatureClassifierExample;
import nl.esciencecenter.eecology.classification.db.classification.FeatureClassifierKey;
import org.apache.ibatis.annotations.Param;

public interface FeatureClassifierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(FeatureClassifierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(FeatureClassifierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByPrimaryKey(FeatureClassifierKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(FeatureClassifierKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(FeatureClassifierKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<FeatureClassifierKey> selectByExample(FeatureClassifierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") FeatureClassifierKey record, @Param("example") FeatureClassifierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") FeatureClassifierKey record, @Param("example") FeatureClassifierExample example);
}