package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.FeatureClassifierFeatureIdKey;
import nl.esciencecenter.eecology.classification.db.classification.FeatureClassifierFeatureIdKeyExample;
import org.apache.ibatis.annotations.Param;

public interface FeatureClassifierFeatureIdKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier_feature_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(FeatureClassifierFeatureIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier_feature_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(FeatureClassifierFeatureIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier_feature_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(FeatureClassifierFeatureIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier_feature_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(FeatureClassifierFeatureIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier_feature_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<FeatureClassifierFeatureIdKey> selectByExample(FeatureClassifierFeatureIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier_feature_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") FeatureClassifierFeatureIdKey record, @Param("example") FeatureClassifierFeatureIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_classifier_feature_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") FeatureClassifierFeatureIdKey record, @Param("example") FeatureClassifierFeatureIdKeyExample example);
}