package nl.esciencecenter.eecology.classification.db.model.classification;

public class FeatureValuePkey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.feature_value_pkey.feature_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Integer feature_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.feature_value_pkey.segment_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Integer segment_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.feature_value_pkey.feature_id
     *
     * @return the value of classification.feature_value_pkey.feature_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Integer getFeature_id() {
        return feature_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.feature_value_pkey.feature_id
     *
     * @param feature_id the value for classification.feature_value_pkey.feature_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setFeature_id(Integer feature_id) {
        this.feature_id = feature_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.feature_value_pkey.segment_id
     *
     * @return the value of classification.feature_value_pkey.segment_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Integer getSegment_id() {
        return segment_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.feature_value_pkey.segment_id
     *
     * @param segment_id the value for classification.feature_value_pkey.segment_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setSegment_id(Integer segment_id) {
        this.segment_id = segment_id;
    }
}