package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.FeatureValueFeatureIdKey;
import nl.esciencecenter.eecology.classification.db.classification.FeatureValueFeatureIdKeyExample;
import org.apache.ibatis.annotations.Param;

public interface FeatureValueFeatureIdKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_feature_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(FeatureValueFeatureIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_feature_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(FeatureValueFeatureIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_feature_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(FeatureValueFeatureIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_feature_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(FeatureValueFeatureIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_feature_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<FeatureValueFeatureIdKey> selectByExample(FeatureValueFeatureIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_feature_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") FeatureValueFeatureIdKey record, @Param("example") FeatureValueFeatureIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_feature_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") FeatureValueFeatureIdKey record, @Param("example") FeatureValueFeatureIdKeyExample example);
}