package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.FeatureValueSegmentIdKey;
import nl.esciencecenter.eecology.classification.db.classification.FeatureValueSegmentIdKeyExample;
import org.apache.ibatis.annotations.Param;

public interface FeatureValueSegmentIdKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(FeatureValueSegmentIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(FeatureValueSegmentIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(FeatureValueSegmentIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(FeatureValueSegmentIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<FeatureValueSegmentIdKey> selectByExample(FeatureValueSegmentIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") FeatureValueSegmentIdKey record, @Param("example") FeatureValueSegmentIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.feature_value_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") FeatureValueSegmentIdKey record, @Param("example") FeatureValueSegmentIdKeyExample example);
}