package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.JobClassifierIdKey;
import nl.esciencecenter.eecology.classification.db.classification.JobClassifierIdKeyExample;
import org.apache.ibatis.annotations.Param;

public interface JobClassifierIdKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_classifier_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(JobClassifierIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_classifier_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(JobClassifierIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_classifier_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(JobClassifierIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_classifier_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(JobClassifierIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_classifier_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<JobClassifierIdKey> selectByExample(JobClassifierIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_classifier_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") JobClassifierIdKey record, @Param("example") JobClassifierIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_classifier_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") JobClassifierIdKey record, @Param("example") JobClassifierIdKeyExample example);
}