package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JobExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table classification.job
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table classification.job
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table classification.job
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public JobExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table classification.job
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJob_idIsNull() {
            addCriterion("job_id is null");
            return (Criteria) this;
        }

        public Criteria andJob_idIsNotNull() {
            addCriterion("job_id is not null");
            return (Criteria) this;
        }

        public Criteria andJob_idEqualTo(Integer value) {
            addCriterion("job_id =", value, "job_id");
            return (Criteria) this;
        }

        public Criteria andJob_idNotEqualTo(Integer value) {
            addCriterion("job_id <>", value, "job_id");
            return (Criteria) this;
        }

        public Criteria andJob_idGreaterThan(Integer value) {
            addCriterion("job_id >", value, "job_id");
            return (Criteria) this;
        }

        public Criteria andJob_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("job_id >=", value, "job_id");
            return (Criteria) this;
        }

        public Criteria andJob_idLessThan(Integer value) {
            addCriterion("job_id <", value, "job_id");
            return (Criteria) this;
        }

        public Criteria andJob_idLessThanOrEqualTo(Integer value) {
            addCriterion("job_id <=", value, "job_id");
            return (Criteria) this;
        }

        public Criteria andJob_idIn(List<Integer> values) {
            addCriterion("job_id in", values, "job_id");
            return (Criteria) this;
        }

        public Criteria andJob_idNotIn(List<Integer> values) {
            addCriterion("job_id not in", values, "job_id");
            return (Criteria) this;
        }

        public Criteria andJob_idBetween(Integer value1, Integer value2) {
            addCriterion("job_id between", value1, value2, "job_id");
            return (Criteria) this;
        }

        public Criteria andJob_idNotBetween(Integer value1, Integer value2) {
            addCriterion("job_id not between", value1, value2, "job_id");
            return (Criteria) this;
        }

        public Criteria andClassifier_idIsNull() {
            addCriterion("classifier_id is null");
            return (Criteria) this;
        }

        public Criteria andClassifier_idIsNotNull() {
            addCriterion("classifier_id is not null");
            return (Criteria) this;
        }

        public Criteria andClassifier_idEqualTo(Integer value) {
            addCriterion("classifier_id =", value, "classifier_id");
            return (Criteria) this;
        }

        public Criteria andClassifier_idNotEqualTo(Integer value) {
            addCriterion("classifier_id <>", value, "classifier_id");
            return (Criteria) this;
        }

        public Criteria andClassifier_idGreaterThan(Integer value) {
            addCriterion("classifier_id >", value, "classifier_id");
            return (Criteria) this;
        }

        public Criteria andClassifier_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("classifier_id >=", value, "classifier_id");
            return (Criteria) this;
        }

        public Criteria andClassifier_idLessThan(Integer value) {
            addCriterion("classifier_id <", value, "classifier_id");
            return (Criteria) this;
        }

        public Criteria andClassifier_idLessThanOrEqualTo(Integer value) {
            addCriterion("classifier_id <=", value, "classifier_id");
            return (Criteria) this;
        }

        public Criteria andClassifier_idIn(List<Integer> values) {
            addCriterion("classifier_id in", values, "classifier_id");
            return (Criteria) this;
        }

        public Criteria andClassifier_idNotIn(List<Integer> values) {
            addCriterion("classifier_id not in", values, "classifier_id");
            return (Criteria) this;
        }

        public Criteria andClassifier_idBetween(Integer value1, Integer value2) {
            addCriterion("classifier_id between", value1, value2, "classifier_id");
            return (Criteria) this;
        }

        public Criteria andClassifier_idNotBetween(Integer value1, Integer value2) {
            addCriterion("classifier_id not between", value1, value2, "classifier_id");
            return (Criteria) this;
        }

        public Criteria andCreated_onIsNull() {
            addCriterion("created_on is null");
            return (Criteria) this;
        }

        public Criteria andCreated_onIsNotNull() {
            addCriterion("created_on is not null");
            return (Criteria) this;
        }

        public Criteria andCreated_onEqualTo(Date value) {
            addCriterion("created_on =", value, "created_on");
            return (Criteria) this;
        }

        public Criteria andCreated_onNotEqualTo(Date value) {
            addCriterion("created_on <>", value, "created_on");
            return (Criteria) this;
        }

        public Criteria andCreated_onGreaterThan(Date value) {
            addCriterion("created_on >", value, "created_on");
            return (Criteria) this;
        }

        public Criteria andCreated_onGreaterThanOrEqualTo(Date value) {
            addCriterion("created_on >=", value, "created_on");
            return (Criteria) this;
        }

        public Criteria andCreated_onLessThan(Date value) {
            addCriterion("created_on <", value, "created_on");
            return (Criteria) this;
        }

        public Criteria andCreated_onLessThanOrEqualTo(Date value) {
            addCriterion("created_on <=", value, "created_on");
            return (Criteria) this;
        }

        public Criteria andCreated_onIn(List<Date> values) {
            addCriterion("created_on in", values, "created_on");
            return (Criteria) this;
        }

        public Criteria andCreated_onNotIn(List<Date> values) {
            addCriterion("created_on not in", values, "created_on");
            return (Criteria) this;
        }

        public Criteria andCreated_onBetween(Date value1, Date value2) {
            addCriterion("created_on between", value1, value2, "created_on");
            return (Criteria) this;
        }

        public Criteria andCreated_onNotBetween(Date value1, Date value2) {
            addCriterion("created_on not between", value1, value2, "created_on");
            return (Criteria) this;
        }

        public Criteria andCreated_byIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreated_byIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreated_byEqualTo(String value) {
            addCriterion("created_by =", value, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byNotEqualTo(String value) {
            addCriterion("created_by <>", value, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byGreaterThan(String value) {
            addCriterion("created_by >", value, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byLessThan(String value) {
            addCriterion("created_by <", value, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byLike(String value) {
            addCriterion("created_by like", value, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byNotLike(String value) {
            addCriterion("created_by not like", value, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byIn(List<String> values) {
            addCriterion("created_by in", values, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byNotIn(List<String> values) {
            addCriterion("created_by not in", values, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "created_by");
            return (Criteria) this;
        }

        public Criteria andCreated_byNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "created_by");
            return (Criteria) this;
        }

        public Criteria andParent_job_idIsNull() {
            addCriterion("parent_job_id is null");
            return (Criteria) this;
        }

        public Criteria andParent_job_idIsNotNull() {
            addCriterion("parent_job_id is not null");
            return (Criteria) this;
        }

        public Criteria andParent_job_idEqualTo(Integer value) {
            addCriterion("parent_job_id =", value, "parent_job_id");
            return (Criteria) this;
        }

        public Criteria andParent_job_idNotEqualTo(Integer value) {
            addCriterion("parent_job_id <>", value, "parent_job_id");
            return (Criteria) this;
        }

        public Criteria andParent_job_idGreaterThan(Integer value) {
            addCriterion("parent_job_id >", value, "parent_job_id");
            return (Criteria) this;
        }

        public Criteria andParent_job_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("parent_job_id >=", value, "parent_job_id");
            return (Criteria) this;
        }

        public Criteria andParent_job_idLessThan(Integer value) {
            addCriterion("parent_job_id <", value, "parent_job_id");
            return (Criteria) this;
        }

        public Criteria andParent_job_idLessThanOrEqualTo(Integer value) {
            addCriterion("parent_job_id <=", value, "parent_job_id");
            return (Criteria) this;
        }

        public Criteria andParent_job_idIn(List<Integer> values) {
            addCriterion("parent_job_id in", values, "parent_job_id");
            return (Criteria) this;
        }

        public Criteria andParent_job_idNotIn(List<Integer> values) {
            addCriterion("parent_job_id not in", values, "parent_job_id");
            return (Criteria) this;
        }

        public Criteria andParent_job_idBetween(Integer value1, Integer value2) {
            addCriterion("parent_job_id between", value1, value2, "parent_job_id");
            return (Criteria) this;
        }

        public Criteria andParent_job_idNotBetween(Integer value1, Integer value2) {
            addCriterion("parent_job_id not between", value1, value2, "parent_job_id");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table classification.job
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 07 16:43:08 CEST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table classification.job
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}