package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.JobJobIdSeq;
import nl.esciencecenter.eecology.classification.db.classification.JobJobIdSeqExample;
import org.apache.ibatis.annotations.Param;

public interface JobJobIdSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_job_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(JobJobIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_job_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(JobJobIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_job_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(JobJobIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_job_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(JobJobIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_job_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<JobJobIdSeq> selectByExample(JobJobIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_job_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") JobJobIdSeq record, @Param("example") JobJobIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_job_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") JobJobIdSeq record, @Param("example") JobJobIdSeqExample example);
}