package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.Job;
import nl.esciencecenter.eecology.classification.db.classification.JobExample;
import org.apache.ibatis.annotations.Param;

public interface JobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByPrimaryKey(Integer job_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<Job> selectByExample(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    Job selectByPrimaryKey(Integer job_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") Job record, @Param("example") JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") Job record, @Param("example") JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByPrimaryKeySelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByPrimaryKey(Job record);
}