package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.JobParentJobIdKey;
import nl.esciencecenter.eecology.classification.db.classification.JobParentJobIdKeyExample;
import org.apache.ibatis.annotations.Param;

public interface JobParentJobIdKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_parent_job_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(JobParentJobIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_parent_job_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(JobParentJobIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_parent_job_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(JobParentJobIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_parent_job_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(JobParentJobIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_parent_job_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<JobParentJobIdKey> selectByExample(JobParentJobIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_parent_job_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") JobParentJobIdKey record, @Param("example") JobParentJobIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_parent_job_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") JobParentJobIdKey record, @Param("example") JobParentJobIdKeyExample example);
}