package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.JobSelectionJobIdKey;
import nl.esciencecenter.eecology.classification.db.classification.JobSelectionJobIdKeyExample;
import org.apache.ibatis.annotations.Param;

public interface JobSelectionJobIdKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection_job_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(JobSelectionJobIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection_job_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(JobSelectionJobIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection_job_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(JobSelectionJobIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection_job_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(JobSelectionJobIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection_job_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<JobSelectionJobIdKey> selectByExample(JobSelectionJobIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection_job_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") JobSelectionJobIdKey record, @Param("example") JobSelectionJobIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection_job_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") JobSelectionJobIdKey record, @Param("example") JobSelectionJobIdKeyExample example);
}