package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.JobSelectionPkey;
import nl.esciencecenter.eecology.classification.db.classification.JobSelectionPkeyExample;
import org.apache.ibatis.annotations.Param;

public interface JobSelectionPkeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(JobSelectionPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(JobSelectionPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(JobSelectionPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(JobSelectionPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<JobSelectionPkey> selectByExample(JobSelectionPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") JobSelectionPkey record, @Param("example") JobSelectionPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.job_selection_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") JobSelectionPkey record, @Param("example") JobSelectionPkeyExample example);
}