package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.LabelLabelSchemaIdKey;
import nl.esciencecenter.eecology.classification.db.classification.LabelLabelSchemaIdKeyExample;
import org.apache.ibatis.annotations.Param;

public interface LabelLabelSchemaIdKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(LabelLabelSchemaIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(LabelLabelSchemaIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(LabelLabelSchemaIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(LabelLabelSchemaIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<LabelLabelSchemaIdKey> selectByExample(LabelLabelSchemaIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") LabelLabelSchemaIdKey record, @Param("example") LabelLabelSchemaIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") LabelLabelSchemaIdKey record, @Param("example") LabelLabelSchemaIdKeyExample example);
}