package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.LabelLabelIdKey;
import nl.esciencecenter.eecology.classification.db.classification.LabelLabelIdKeyExample;
import org.apache.ibatis.annotations.Param;

public interface LabelLabelIdKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(LabelLabelIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(LabelLabelIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(LabelLabelIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(LabelLabelIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<LabelLabelIdKey> selectByExample(LabelLabelIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") LabelLabelIdKey record, @Param("example") LabelLabelIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_label_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") LabelLabelIdKey record, @Param("example") LabelLabelIdKeyExample example);
}