package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.LabelRemap;
import nl.esciencecenter.eecology.classification.db.classification.LabelRemapExample;
import nl.esciencecenter.eecology.classification.db.classification.LabelRemapKey;
import org.apache.ibatis.annotations.Param;

public interface LabelRemapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(LabelRemapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(LabelRemapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByPrimaryKey(LabelRemapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(LabelRemap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(LabelRemap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<LabelRemap> selectByExample(LabelRemapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    LabelRemap selectByPrimaryKey(LabelRemapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") LabelRemap record, @Param("example") LabelRemapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") LabelRemap record, @Param("example") LabelRemapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByPrimaryKeySelective(LabelRemap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByPrimaryKey(LabelRemap record);
}