package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.LabelRemapTargetLabelIdKey;
import nl.esciencecenter.eecology.classification.db.classification.LabelRemapTargetLabelIdKeyExample;
import org.apache.ibatis.annotations.Param;

public interface LabelRemapTargetLabelIdKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_target_label_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(LabelRemapTargetLabelIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_target_label_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(LabelRemapTargetLabelIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_target_label_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(LabelRemapTargetLabelIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_target_label_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(LabelRemapTargetLabelIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_target_label_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<LabelRemapTargetLabelIdKey> selectByExample(LabelRemapTargetLabelIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_target_label_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") LabelRemapTargetLabelIdKey record, @Param("example") LabelRemapTargetLabelIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_target_label_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") LabelRemapTargetLabelIdKey record, @Param("example") LabelRemapTargetLabelIdKeyExample example);
}