package nl.esciencecenter.eecology.classification.db.model.classification;

public class LabelSchemaPkey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.label_schema_pkey.label_schema_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Integer label_schema_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.label_schema_pkey.label_schema_id
     *
     * @return the value of classification.label_schema_pkey.label_schema_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Integer getLabel_schema_id() {
        return label_schema_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.label_schema_pkey.label_schema_id
     *
     * @param label_schema_id the value for classification.label_schema_pkey.label_schema_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setLabel_schema_id(Integer label_schema_id) {
        this.label_schema_id = label_schema_id;
    }
}