package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.LabelRemapTargetLabelSchemaIdKey;
import nl.esciencecenter.eecology.classification.db.classification.LabelRemapTargetLabelSchemaIdKeyExample;
import org.apache.ibatis.annotations.Param;

public interface LabelRemapTargetLabelSchemaIdKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_target_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(LabelRemapTargetLabelSchemaIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_target_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(LabelRemapTargetLabelSchemaIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_target_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(LabelRemapTargetLabelSchemaIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_target_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(LabelRemapTargetLabelSchemaIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_target_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<LabelRemapTargetLabelSchemaIdKey> selectByExample(LabelRemapTargetLabelSchemaIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_target_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") LabelRemapTargetLabelSchemaIdKey record, @Param("example") LabelRemapTargetLabelSchemaIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_remap_target_label_schema_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") LabelRemapTargetLabelSchemaIdKey record, @Param("example") LabelRemapTargetLabelSchemaIdKeyExample example);
}