package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.LabelSchemaLabelSchemaIdSeq;
import nl.esciencecenter.eecology.classification.db.classification.LabelSchemaLabelSchemaIdSeqExample;
import org.apache.ibatis.annotations.Param;

public interface LabelSchemaLabelSchemaIdSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema_label_schema_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(LabelSchemaLabelSchemaIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema_label_schema_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(LabelSchemaLabelSchemaIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema_label_schema_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(LabelSchemaLabelSchemaIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema_label_schema_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(LabelSchemaLabelSchemaIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema_label_schema_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<LabelSchemaLabelSchemaIdSeq> selectByExample(LabelSchemaLabelSchemaIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema_label_schema_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") LabelSchemaLabelSchemaIdSeq record, @Param("example") LabelSchemaLabelSchemaIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema_label_schema_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") LabelSchemaLabelSchemaIdSeq record, @Param("example") LabelSchemaLabelSchemaIdSeqExample example);
}