package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.LabelSchemaPkey;
import nl.esciencecenter.eecology.classification.db.classification.LabelSchemaPkeyExample;
import org.apache.ibatis.annotations.Param;

public interface LabelSchemaPkeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(LabelSchemaPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(LabelSchemaPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(LabelSchemaPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(LabelSchemaPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<LabelSchemaPkey> selectByExample(LabelSchemaPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") LabelSchemaPkey record, @Param("example") LabelSchemaPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.label_schema_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") LabelSchemaPkey record, @Param("example") LabelSchemaPkeyExample example);
}