package nl.esciencecenter.eecology.classification.db.model.classification;

public class Label extends LabelKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.label.name
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.label.red
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Short red;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.label.green
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Short green;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.label.blue
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Short blue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.label.description
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.label.name
     *
     * @return the value of classification.label.name
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.label.name
     *
     * @param name the value for classification.label.name
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.label.red
     *
     * @return the value of classification.label.red
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Short getRed() {
        return red;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.label.red
     *
     * @param red the value for classification.label.red
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setRed(Short red) {
        this.red = red;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.label.green
     *
     * @return the value of classification.label.green
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Short getGreen() {
        return green;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.label.green
     *
     * @param green the value for classification.label.green
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setGreen(Short green) {
        this.green = green;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.label.blue
     *
     * @return the value of classification.label.blue
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Short getBlue() {
        return blue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.label.blue
     *
     * @param blue the value for classification.label.blue
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setBlue(Short blue) {
        this.blue = blue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.label.description
     *
     * @return the value of classification.label.description
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.label.description
     *
     * @param description the value for classification.label.description
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}