package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.Date;

public class Segment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.segment.segment_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Integer segment_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.segment.device_info_serial
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Integer device_info_serial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.segment.date_time
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Date date_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.segment.segment_id
     *
     * @return the value of classification.segment.segment_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Integer getSegment_id() {
        return segment_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.segment.segment_id
     *
     * @param segment_id the value for classification.segment.segment_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setSegment_id(Integer segment_id) {
        this.segment_id = segment_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.segment.device_info_serial
     *
     * @return the value of classification.segment.device_info_serial
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Integer getDevice_info_serial() {
        return device_info_serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.segment.device_info_serial
     *
     * @param device_info_serial the value for classification.segment.device_info_serial
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setDevice_info_serial(Integer device_info_serial) {
        this.device_info_serial = device_info_serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.segment.date_time
     *
     * @return the value of classification.segment.date_time
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Date getDate_time() {
        return date_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.segment.date_time
     *
     * @param date_time the value for classification.segment.date_time
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setDate_time(Date date_time) {
        this.date_time = date_time;
    }
}