package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SegmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table classification.segment
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table classification.segment
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table classification.segment
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public SegmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table classification.segment
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSegment_idIsNull() {
            addCriterion("segment_id is null");
            return (Criteria) this;
        }

        public Criteria andSegment_idIsNotNull() {
            addCriterion("segment_id is not null");
            return (Criteria) this;
        }

        public Criteria andSegment_idEqualTo(Integer value) {
            addCriterion("segment_id =", value, "segment_id");
            return (Criteria) this;
        }

        public Criteria andSegment_idNotEqualTo(Integer value) {
            addCriterion("segment_id <>", value, "segment_id");
            return (Criteria) this;
        }

        public Criteria andSegment_idGreaterThan(Integer value) {
            addCriterion("segment_id >", value, "segment_id");
            return (Criteria) this;
        }

        public Criteria andSegment_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("segment_id >=", value, "segment_id");
            return (Criteria) this;
        }

        public Criteria andSegment_idLessThan(Integer value) {
            addCriterion("segment_id <", value, "segment_id");
            return (Criteria) this;
        }

        public Criteria andSegment_idLessThanOrEqualTo(Integer value) {
            addCriterion("segment_id <=", value, "segment_id");
            return (Criteria) this;
        }

        public Criteria andSegment_idIn(List<Integer> values) {
            addCriterion("segment_id in", values, "segment_id");
            return (Criteria) this;
        }

        public Criteria andSegment_idNotIn(List<Integer> values) {
            addCriterion("segment_id not in", values, "segment_id");
            return (Criteria) this;
        }

        public Criteria andSegment_idBetween(Integer value1, Integer value2) {
            addCriterion("segment_id between", value1, value2, "segment_id");
            return (Criteria) this;
        }

        public Criteria andSegment_idNotBetween(Integer value1, Integer value2) {
            addCriterion("segment_id not between", value1, value2, "segment_id");
            return (Criteria) this;
        }

        public Criteria andDevice_info_serialIsNull() {
            addCriterion("device_info_serial is null");
            return (Criteria) this;
        }

        public Criteria andDevice_info_serialIsNotNull() {
            addCriterion("device_info_serial is not null");
            return (Criteria) this;
        }

        public Criteria andDevice_info_serialEqualTo(Integer value) {
            addCriterion("device_info_serial =", value, "device_info_serial");
            return (Criteria) this;
        }

        public Criteria andDevice_info_serialNotEqualTo(Integer value) {
            addCriterion("device_info_serial <>", value, "device_info_serial");
            return (Criteria) this;
        }

        public Criteria andDevice_info_serialGreaterThan(Integer value) {
            addCriterion("device_info_serial >", value, "device_info_serial");
            return (Criteria) this;
        }

        public Criteria andDevice_info_serialGreaterThanOrEqualTo(Integer value) {
            addCriterion("device_info_serial >=", value, "device_info_serial");
            return (Criteria) this;
        }

        public Criteria andDevice_info_serialLessThan(Integer value) {
            addCriterion("device_info_serial <", value, "device_info_serial");
            return (Criteria) this;
        }

        public Criteria andDevice_info_serialLessThanOrEqualTo(Integer value) {
            addCriterion("device_info_serial <=", value, "device_info_serial");
            return (Criteria) this;
        }

        public Criteria andDevice_info_serialIn(List<Integer> values) {
            addCriterion("device_info_serial in", values, "device_info_serial");
            return (Criteria) this;
        }

        public Criteria andDevice_info_serialNotIn(List<Integer> values) {
            addCriterion("device_info_serial not in", values, "device_info_serial");
            return (Criteria) this;
        }

        public Criteria andDevice_info_serialBetween(Integer value1, Integer value2) {
            addCriterion("device_info_serial between", value1, value2, "device_info_serial");
            return (Criteria) this;
        }

        public Criteria andDevice_info_serialNotBetween(Integer value1, Integer value2) {
            addCriterion("device_info_serial not between", value1, value2, "device_info_serial");
            return (Criteria) this;
        }

        public Criteria andDate_timeIsNull() {
            addCriterion("date_time is null");
            return (Criteria) this;
        }

        public Criteria andDate_timeIsNotNull() {
            addCriterion("date_time is not null");
            return (Criteria) this;
        }

        public Criteria andDate_timeEqualTo(Date value) {
            addCriterion("date_time =", value, "date_time");
            return (Criteria) this;
        }

        public Criteria andDate_timeNotEqualTo(Date value) {
            addCriterion("date_time <>", value, "date_time");
            return (Criteria) this;
        }

        public Criteria andDate_timeGreaterThan(Date value) {
            addCriterion("date_time >", value, "date_time");
            return (Criteria) this;
        }

        public Criteria andDate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("date_time >=", value, "date_time");
            return (Criteria) this;
        }

        public Criteria andDate_timeLessThan(Date value) {
            addCriterion("date_time <", value, "date_time");
            return (Criteria) this;
        }

        public Criteria andDate_timeLessThanOrEqualTo(Date value) {
            addCriterion("date_time <=", value, "date_time");
            return (Criteria) this;
        }

        public Criteria andDate_timeIn(List<Date> values) {
            addCriterion("date_time in", values, "date_time");
            return (Criteria) this;
        }

        public Criteria andDate_timeNotIn(List<Date> values) {
            addCriterion("date_time not in", values, "date_time");
            return (Criteria) this;
        }

        public Criteria andDate_timeBetween(Date value1, Date value2) {
            addCriterion("date_time between", value1, value2, "date_time");
            return (Criteria) this;
        }

        public Criteria andDate_timeNotBetween(Date value1, Date value2) {
            addCriterion("date_time not between", value1, value2, "date_time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table classification.segment
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 07 16:43:08 CEST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table classification.segment
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}