package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.Segment;
import nl.esciencecenter.eecology.classification.db.classification.SegmentExample;
import org.apache.ibatis.annotations.Param;

public interface SegmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(SegmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(SegmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByPrimaryKey(Integer segment_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(Segment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(Segment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<Segment> selectByExample(SegmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    Segment selectByPrimaryKey(Integer segment_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") Segment record, @Param("example") SegmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") Segment record, @Param("example") SegmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByPrimaryKeySelective(Segment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByPrimaryKey(Segment record);
}