package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.SegmentAcceleration;
import nl.esciencecenter.eecology.classification.db.classification.SegmentAccelerationExample;
import org.apache.ibatis.annotations.Param;

public interface SegmentAccelerationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(SegmentAccelerationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(SegmentAccelerationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByPrimaryKey(Integer segment_acceleration_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(SegmentAcceleration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(SegmentAcceleration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<SegmentAcceleration> selectByExample(SegmentAccelerationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    SegmentAcceleration selectByPrimaryKey(Integer segment_acceleration_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") SegmentAcceleration record, @Param("example") SegmentAccelerationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") SegmentAcceleration record, @Param("example") SegmentAccelerationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByPrimaryKeySelective(SegmentAcceleration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByPrimaryKey(SegmentAcceleration record);
}