package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.SegmentAccelerationSegmentIdKey;
import nl.esciencecenter.eecology.classification.db.classification.SegmentAccelerationSegmentIdKeyExample;
import org.apache.ibatis.annotations.Param;

public interface SegmentAccelerationSegmentIdKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(SegmentAccelerationSegmentIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(SegmentAccelerationSegmentIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(SegmentAccelerationSegmentIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(SegmentAccelerationSegmentIdKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<SegmentAccelerationSegmentIdKey> selectByExample(SegmentAccelerationSegmentIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") SegmentAccelerationSegmentIdKey record, @Param("example") SegmentAccelerationSegmentIdKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_acceleration_segment_id_key
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") SegmentAccelerationSegmentIdKey record, @Param("example") SegmentAccelerationSegmentIdKeyExample example);
}