package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.SegmentPkey;
import nl.esciencecenter.eecology.classification.db.classification.SegmentPkeyExample;
import org.apache.ibatis.annotations.Param;

public interface SegmentPkeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(SegmentPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(SegmentPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(SegmentPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(SegmentPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<SegmentPkey> selectByExample(SegmentPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") SegmentPkey record, @Param("example") SegmentPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") SegmentPkey record, @Param("example") SegmentPkeyExample example);
}