package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.SegmentatorPkey;
import nl.esciencecenter.eecology.classification.db.classification.SegmentatorPkeyExample;
import org.apache.ibatis.annotations.Param;

public interface SegmentatorPkeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(SegmentatorPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(SegmentatorPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(SegmentatorPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(SegmentatorPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<SegmentatorPkey> selectByExample(SegmentatorPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") SegmentatorPkey record, @Param("example") SegmentatorPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator_pkey
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") SegmentatorPkey record, @Param("example") SegmentatorPkeyExample example);
}