package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.Segmentator;
import nl.esciencecenter.eecology.classification.db.classification.SegmentatorExample;
import org.apache.ibatis.annotations.Param;

public interface SegmentatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(SegmentatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(SegmentatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByPrimaryKey(Integer segmentator_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(Segmentator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(Segmentator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<Segmentator> selectByExample(SegmentatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    Segmentator selectByPrimaryKey(Integer segmentator_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") Segmentator record, @Param("example") SegmentatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") Segmentator record, @Param("example") SegmentatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByPrimaryKeySelective(Segmentator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segmentator
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByPrimaryKey(Segmentator record);
}