package nl.esciencecenter.eecology.classification.db.model.classification;

public class SegmentatorNameKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.segmentator_name_key.name
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.segmentator_name_key.name
     *
     * @return the value of classification.segmentator_name_key.name
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.segmentator_name_key.name
     *
     * @param name the value for classification.segmentator_name_key.name
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}