package nl.esciencecenter.eecology.classification.db.model.classification;

public class SegmentatorPkey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.segmentator_pkey.segmentator_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    private Integer segmentator_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.segmentator_pkey.segmentator_id
     *
     * @return the value of classification.segmentator_pkey.segmentator_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public Integer getSegmentator_id() {
        return segmentator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.segmentator_pkey.segmentator_id
     *
     * @param segmentator_id the value for classification.segmentator_pkey.segmentator_id
     *
     * @mbggenerated Mon Jul 07 16:43:08 CEST 2014
     */
    public void setSegmentator_id(Integer segmentator_id) {
        this.segmentator_id = segmentator_id;
    }
}