package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.SegmentSegmentIdSeq;
import nl.esciencecenter.eecology.classification.db.classification.SegmentSegmentIdSeqExample;
import org.apache.ibatis.annotations.Param;

public interface SegmentSegmentIdSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_segment_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(SegmentSegmentIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_segment_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(SegmentSegmentIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_segment_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(SegmentSegmentIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_segment_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(SegmentSegmentIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_segment_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<SegmentSegmentIdSeq> selectByExample(SegmentSegmentIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_segment_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") SegmentSegmentIdSeq record, @Param("example") SegmentSegmentIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.segment_segment_id_seq
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") SegmentSegmentIdSeq record, @Param("example") SegmentSegmentIdSeqExample example);
}