package nl.esciencecenter.eecology.classification.db.model.classification;

import java.util.List;
import nl.esciencecenter.eecology.classification.db.classification.SetU;
import nl.esciencecenter.eecology.classification.db.classification.SetUExample;
import org.apache.ibatis.annotations.Param;

public interface SetUMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.set_u
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int countByExample(SetUExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.set_u
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int deleteByExample(SetUExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.set_u
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insert(SetU record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.set_u
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int insertSelective(SetU record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.set_u
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    List<SetU> selectByExample(SetUExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.set_u
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExampleSelective(@Param("record") SetU record, @Param("example") SetUExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification.set_u
     *
     * @mbggenerated Thu Jul 03 09:42:37 CEST 2014
     */
    int updateByExample(@Param("record") SetU record, @Param("example") SetUExample example);
}