package nl.esciencecenter.eecology.classification.db.classification;

public class ClassificationJobIdKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.classification_job_id_key.job_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Integer job_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.classification_job_id_key.job_id
     *
     * @return the value of classification.classification_job_id_key.job_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Integer getJob_id() {
        return job_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classification_job_id_key.job_id
     *
     * @param job_id the value for classification.classification_job_id_key.job_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setJob_id(Integer job_id) {
        this.job_id = job_id;
    }
}