package nl.esciencecenter.eecology.classification.db.classification;

public class ClassificationSegmentIdKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.classification_segment_id_key.segment_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Integer segment_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.classification_segment_id_key.segment_id
     *
     * @return the value of classification.classification_segment_id_key.segment_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Integer getSegment_id() {
        return segment_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classification_segment_id_key.segment_id
     *
     * @param segment_id the value for classification.classification_segment_id_key.segment_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setSegment_id(Integer segment_id) {
        this.segment_id = segment_id;
    }
}