package nl.esciencecenter.eecology.classification.db.classification;

public class Collection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.collection.collection_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Integer collection_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.collection.type
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.collection.collection_group_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Integer collection_group_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.collection.collection_id
     *
     * @return the value of classification.collection.collection_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Integer getCollection_id() {
        return collection_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.collection.collection_id
     *
     * @param collection_id the value for classification.collection.collection_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setCollection_id(Integer collection_id) {
        this.collection_id = collection_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.collection.type
     *
     * @return the value of classification.collection.type
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.collection.type
     *
     * @param type the value for classification.collection.type
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.collection.collection_group_id
     *
     * @return the value of classification.collection.collection_group_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Integer getCollection_group_id() {
        return collection_group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.collection.collection_group_id
     *
     * @param collection_group_id the value for classification.collection.collection_group_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setCollection_group_id(Integer collection_group_id) {
        this.collection_group_id = collection_group_id;
    }
}