package nl.esciencecenter.eecology.classification.db.classification;

import java.util.Date;

public class CollectionGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.collection_group.collection_group_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Integer collection_group_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.collection_group.name
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.collection_group.description
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.collection_group.created_by
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private String created_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.collection_group.created_on
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Date created_on;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.collection_group.collection_group_id
     *
     * @return the value of classification.collection_group.collection_group_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Integer getCollection_group_id() {
        return collection_group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.collection_group.collection_group_id
     *
     * @param collection_group_id the value for classification.collection_group.collection_group_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setCollection_group_id(Integer collection_group_id) {
        this.collection_group_id = collection_group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.collection_group.name
     *
     * @return the value of classification.collection_group.name
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.collection_group.name
     *
     * @param name the value for classification.collection_group.name
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.collection_group.description
     *
     * @return the value of classification.collection_group.description
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.collection_group.description
     *
     * @param description the value for classification.collection_group.description
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.collection_group.created_by
     *
     * @return the value of classification.collection_group.created_by
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public String getCreated_by() {
        return created_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.collection_group.created_by
     *
     * @param created_by the value for classification.collection_group.created_by
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setCreated_by(String created_by) {
        this.created_by = created_by == null ? null : created_by.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.collection_group.created_on
     *
     * @return the value of classification.collection_group.created_on
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Date getCreated_on() {
        return created_on;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.collection_group.created_on
     *
     * @param created_on the value for classification.collection_group.created_on
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setCreated_on(Date created_on) {
        this.created_on = created_on;
    }
}