package nl.esciencecenter.eecology.classification.db.classification;

public class CollectionPkey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.collection_pkey.collection_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Integer collection_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.collection_pkey.collection_id
     *
     * @return the value of classification.collection_pkey.collection_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Integer getCollection_id() {
        return collection_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.collection_pkey.collection_id
     *
     * @param collection_id the value for classification.collection_pkey.collection_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setCollection_id(Integer collection_id) {
        this.collection_id = collection_id;
    }
}