package nl.esciencecenter.eecology.classification.db.classification;

public class FeatureValue extends FeatureValueKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.feature_value.attribute_value
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Double attribute_value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.feature_value.attribute_value
     *
     * @return the value of classification.feature_value.attribute_value
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Double getAttribute_value() {
        return attribute_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.feature_value.attribute_value
     *
     * @param attribute_value the value for classification.feature_value.attribute_value
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setAttribute_value(Double attribute_value) {
        this.attribute_value = attribute_value;
    }
}