package nl.esciencecenter.eecology.classification.db.classification;

import java.util.Date;

public class Feature {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.feature.feature_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Integer feature_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.feature.name
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.feature.version
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.feature.source
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.feature.expression
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private String expression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.feature.created_by
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private String created_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.feature.created_on
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Date created_on;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.feature.feature_id
     *
     * @return the value of classification.feature.feature_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Integer getFeature_id() {
        return feature_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.feature.feature_id
     *
     * @param feature_id the value for classification.feature.feature_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setFeature_id(Integer feature_id) {
        this.feature_id = feature_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.feature.name
     *
     * @return the value of classification.feature.name
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.feature.name
     *
     * @param name the value for classification.feature.name
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.feature.version
     *
     * @return the value of classification.feature.version
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.feature.version
     *
     * @param version the value for classification.feature.version
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.feature.source
     *
     * @return the value of classification.feature.source
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.feature.source
     *
     * @param source the value for classification.feature.source
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.feature.expression
     *
     * @return the value of classification.feature.expression
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public String getExpression() {
        return expression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.feature.expression
     *
     * @param expression the value for classification.feature.expression
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setExpression(String expression) {
        this.expression = expression == null ? null : expression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.feature.created_by
     *
     * @return the value of classification.feature.created_by
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public String getCreated_by() {
        return created_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.feature.created_by
     *
     * @param created_by the value for classification.feature.created_by
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setCreated_by(String created_by) {
        this.created_by = created_by == null ? null : created_by.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.feature.created_on
     *
     * @return the value of classification.feature.created_on
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Date getCreated_on() {
        return created_on;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.feature.created_on
     *
     * @param created_on the value for classification.feature.created_on
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setCreated_on(Date created_on) {
        this.created_on = created_on;
    }
}