package nl.esciencecenter.eecology.classification.db.classification;

public class FeatureClassifierPkey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.feature_classifier_pkey.feature_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Integer feature_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.feature_classifier_pkey.classifier_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Integer classifier_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.feature_classifier_pkey.feature_id
     *
     * @return the value of classification.feature_classifier_pkey.feature_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Integer getFeature_id() {
        return feature_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.feature_classifier_pkey.feature_id
     *
     * @param feature_id the value for classification.feature_classifier_pkey.feature_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setFeature_id(Integer feature_id) {
        this.feature_id = feature_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.feature_classifier_pkey.classifier_id
     *
     * @return the value of classification.feature_classifier_pkey.classifier_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Integer getClassifier_id() {
        return classifier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.feature_classifier_pkey.classifier_id
     *
     * @param classifier_id the value for classification.feature_classifier_pkey.classifier_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setClassifier_id(Integer classifier_id) {
        this.classifier_id = classifier_id;
    }
}