package nl.esciencecenter.eecology.classification.db.classification;

import java.util.Date;

public class Job {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.job.job_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Integer job_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.job.classifier_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Integer classifier_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.job.created_on
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Date created_on;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.job.created_by
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private String created_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.job.parent_job_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Integer parent_job_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.job.job_id
     *
     * @return the value of classification.job.job_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Integer getJob_id() {
        return job_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.job.job_id
     *
     * @param job_id the value for classification.job.job_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setJob_id(Integer job_id) {
        this.job_id = job_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.job.classifier_id
     *
     * @return the value of classification.job.classifier_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Integer getClassifier_id() {
        return classifier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.job.classifier_id
     *
     * @param classifier_id the value for classification.job.classifier_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setClassifier_id(Integer classifier_id) {
        this.classifier_id = classifier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.job.created_on
     *
     * @return the value of classification.job.created_on
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Date getCreated_on() {
        return created_on;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.job.created_on
     *
     * @param created_on the value for classification.job.created_on
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setCreated_on(Date created_on) {
        this.created_on = created_on;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.job.created_by
     *
     * @return the value of classification.job.created_by
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public String getCreated_by() {
        return created_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.job.created_by
     *
     * @param created_by the value for classification.job.created_by
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setCreated_by(String created_by) {
        this.created_by = created_by == null ? null : created_by.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.job.parent_job_id
     *
     * @return the value of classification.job.parent_job_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Integer getParent_job_id() {
        return parent_job_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.job.parent_job_id
     *
     * @param parent_job_id the value for classification.job.parent_job_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setParent_job_id(Integer parent_job_id) {
        this.parent_job_id = parent_job_id;
    }
}