package nl.esciencecenter.eecology.classification.db.classification;

public class JobClassifierIdKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.job_classifier_id_key.classifier_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Integer classifier_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.job_classifier_id_key.classifier_id
     *
     * @return the value of classification.job_classifier_id_key.classifier_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Integer getClassifier_id() {
        return classifier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.job_classifier_id_key.classifier_id
     *
     * @param classifier_id the value for classification.job_classifier_id_key.classifier_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setClassifier_id(Integer classifier_id) {
        this.classifier_id = classifier_id;
    }
}