package nl.esciencecenter.eecology.classification.db.classification;

public class JobParentJobIdKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.job_parent_job_id_key.parent_job_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Integer parent_job_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.job_parent_job_id_key.parent_job_id
     *
     * @return the value of classification.job_parent_job_id_key.parent_job_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Integer getParent_job_id() {
        return parent_job_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.job_parent_job_id_key.parent_job_id
     *
     * @param parent_job_id the value for classification.job_parent_job_id_key.parent_job_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setParent_job_id(Integer parent_job_id) {
        this.parent_job_id = parent_job_id;
    }
}