package nl.esciencecenter.eecology.classification.db.classification;

public class LabelRemapKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.label_remap.target_label_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Integer target_label_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.label_remap.target_label_schema_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    private Integer target_label_schema_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.label_remap.target_label_id
     *
     * @return the value of classification.label_remap.target_label_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Integer getTarget_label_id() {
        return target_label_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.label_remap.target_label_id
     *
     * @param target_label_id the value for classification.label_remap.target_label_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setTarget_label_id(Integer target_label_id) {
        this.target_label_id = target_label_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.label_remap.target_label_schema_id
     *
     * @return the value of classification.label_remap.target_label_schema_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public Integer getTarget_label_schema_id() {
        return target_label_schema_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.label_remap.target_label_schema_id
     *
     * @param target_label_schema_id the value for classification.label_remap.target_label_schema_id
     *
     * @mbggenerated Wed Jul 02 17:44:44 CEST 2014
     */
    public void setTarget_label_schema_id(Integer target_label_schema_id) {
        this.target_label_schema_id = target_label_schema_id;
    }
}